DROP DATABASE IF EXISTS REGISTRARSE;
CREATE DATABASE REGISTRARSE;
USE REGISTRARSE;

CREATE TABLE AREA(
cveArea CHAR(1) PRIMARY KEY NOT NULL,
nomArea VARCHAR(25) NOT NULL 
);
CREATE TABLE ESPECIALIDAD(
cveEsp CHAR(25) PRIMARY KEY NOT NULL,
nomEsp VARCHAR(25) NOT NULL,
cveArea CHAR(1) NOT NULL,
FOREIGN KEY (cveArea) REFERENCES AREA (cveArea)
            ON UPDATE CASCADE 
);
INSERT INTO AREA VALUES('H','Hombre');
INSERT INTO AREA VALUES('M','Mujer');